apiVersion: v1
kind: Template
metadata:
  annotations:
    iconClass: icon-java
    tags: microservice,jboss
  name: pipeline-scm
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "${DEPLOYMENT_NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
    name: ${PIPELINE_NAME}
  spec:
    source:
      git:
        uri: ${GIT_URI}
        ref: ${GIT_REF}
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${JENKINS_FILE}
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic
parameters:
- displayName: Pipeline Name
  name: PIPELINE_NAME
  required: true
  value: cart-pipeline
- displayName: Deployment Name
  name: DEPLOYMENT_NAME
  required: true
  value: cart
- displayName: Git Repository for Pipeline
  name: GIT_URI
  required: true
  value: https://github.com/siamaksade/cart-service.git
- description: Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
- displayName: Jenkinsfile Path
  name: JENKINS_FILE
  value: Jenkinsfile
