apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "cart", "namespace": "", "kind": "DeploymentConfig"}]'
  name: cart-pipeline-git
spec:
  source:
    git:
      uri: https://gitlab-ce-lab-infra.apps.127.0.0.1.nip.io/developer/pipelines.git
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy: {}
  triggers:
  - generic:
      secret: FiArdDBH
    type: Generic