apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "cart", "namespace": "", "kind": "DeploymentConfig"}]'
  name: cart-pipeline-git
spec:
  source:
    git:
      uri: http://gogs-lab-infra.apps.192.168.122.10.nip.io/developer/cart-service.git
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy: {}
  triggers:
  - generic:
      secret: FiArdDBH
    type: Generic
