apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cart-green
      application: coolstore
      component: cart-green
    name: cart-green
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: cart-green
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: coolstore
      component: cart-green
    name: cart-green
  spec:
    replicas: 1
    selector:
      deploymentconfig: cart-green
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: coolstore
          component: cart-green
          deploymentconfig: cart-green
        name: cart-green
      spec:
        containers:
        - env:
          - name: CATALOG_ENDPOINT
            value: http://catalog:8080
          image: cart
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: cart-green
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 45
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cart-green
        from:
          kind: ImageStreamTag
          name: cart:prod-green
          namespace: prod
      type: ImageChange
    - type: ConfigChange